### ISSUE TITLE
Project not starting on npm start, client id option is required

### ISSUE THREAD

**Issue by dev-sankhadip** [NJACKWinterOfCode/sociofolio#2]
![Screenshot from 2019-12-05 22-53-16](https://user-images.githubusercontent.com/50552816/70258361-1c061680-17b2-11ea-8b31-26f9cba0b094.png)

**Comment by dev-sankhadip** [comment]
@aswinzz please acknowledge this issue, so that i can get my points.

**Comment by Saifu0** [comment]
Same problem @aswinzz

**Comment by aldrin163** [comment]
can i try fixing this?

**Comment by aswinzz** [comment]
Everyone, this uses auth0 for authentication.. create a client in auth0 and use it in src/auth/auth.js
```
auth0 = new auth0.WebAuth({
    domain: 'sociofolio.auth0.com',
    clientID: process.env.REACT_APP_CLIENT_ID,
    redirectUri: process.env.REACT_APP_REDIRECT_URI,
    responseType: 'token id_token',
    scope: 'openid'
  });
```
i will be creating an issue for adding this thing to the readme as well... if anyone is interested they can  work on that.
